package View.Seller;

public enum SellerMenuOptions {
    VIEW_PRODUCTS,ADD_PRODUCTS,UPDATE_PRODUCT_QUANTITY,REMOVE_PRODUCTS,SEARCH_PRODUCTS,VIEW_ORDERS,CHECK_STOCK,VIEW_PROFILE,UPDATE_PROFILE,LOGOUT,DEFAULT
}
