package View.Customer;

public enum CustomerActions {
    VIEW_PRODUCTS,VIEW_CART,REMOVE_FROM_CART,UPDATE_QUANTITY,SEARCH_PRODUCTS,TRACK_ORDERS,REMOVE_AN_ORDER,VIEW_PAST_ORDERS,VIEW_PROFILE,UPDATE_PROFILE,VIEW_SHOP_DETAILS,EXIT,DEFAULT
}
